### ISSUE TITLE
Create and update favicon for website

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd2020#17]
- [x] Create a minimal logo for favicon
 - [x] Update favicon for website

**Comment by SasyaReddi** [comment]
Do any of these look okay?

![favicon](https://user-images.githubusercontent.com/32674099/98170703-73f25380-1f14-11eb-95e7-f0f2ca4c8632.png)
![favicon2](https://user-images.githubusercontent.com/32674099/98170711-75bc1700-1f14-11eb-9996-1afb6a084b0a.png)
![favicon3](https://user-images.githubusercontent.com/32674099/98170830-b9af1c00-1f14-11eb-8a9d-2dc00287752f.png)

**Comment by bhansa** [comment]
Hi @SasyaReddi this looks good, I have asked @subuhani to upload an svg file here so that we can use it.
Once he uploads that, you can update the same in website.

**Comment by bhansa** [comment]
Although, I was thinking to use icon similar to the below image. It will match with our current logo and branding.

![image](https://user-images.githubusercontent.com/9723884/98218918-5b188b00-1f72-11eb-8875-25ed677864af.png)

**Comment by subuhani** [comment]
How about this design @bhansa @SasyaReddi.

![Pyconf-2020-fav-icon](https://user-images.githubusercontent.com/29629943/98221533-c2840a00-1f75-11eb-9f85-c93eabed4da8.png)

![Pyconf-2020-fav-icon-V2](https://user-images.githubusercontent.com/29629943/98221761-0c6cf000-1f76-11eb-9d35-282dab1e6db3.png)

**Comment by SasyaReddi** [comment]
@bhansa Got it, thank you!
@subuhani Looks great! Would just a single ring around the logo make it more visible as a favicon by any chance? (Maybe something like the first image below?)

![favicon4](https://user-images.githubusercontent.com/32674099/98227650-8eace280-1f7d-11eb-8ebd-7db62626adeb.png)
![favicon5](https://user-images.githubusercontent.com/32674099/98227654-8fde0f80-1f7d-11eb-8d17-023ddf1b5fad.png)
![favicon6](https://user-images.githubusercontent.com/32674099/98227656-9076a600-1f7d-11eb-9701-a8bbd5ef84ff.png)

**Comment by SasyaReddi** [comment]
Or, in the first image above, the ring could be a little thicker and the logo a little larger maybe?

**Comment by subuhani** [comment]
@SasyaReddi : Something like this ?
![Pyconf-2020-fav-icon-v3](https://user-images.githubusercontent.com/29629943/98229550-0f6cde00-1f80-11eb-9545-393ccbfcbfbe.png)

**Comment by bhansa** [comment]
Let's go with this one, this looks clean. @subuhani Is it possible to resize it to 512x512 so we can generate other sizes.

Manifest creator: https://app-manifest.firebaseapp.com/

@SasyaReddi Update it once the final image is available and use the above link to generate other sized assets and manifest for the same. Let me know if you need any help.

**Comment by subuhani** [comment]
@bhansa : Here is the 512X512 pixel size, let me know if anything is needed.

![Pyconf 2020 fav icon 512X512-01](https://user-images.githubusercontent.com/29629943/98262708-ee21e700-1fab-11eb-8fe1-f0c95925564e.png)

**Comment by SasyaReddi** [comment]
@subuhani This looks great! Thanks
@bhansa Will get it done. Thank you.

**Comment by bhansa** [comment]
Closing this, as it is completed.
