### ISSUE TITLE
Fix ci build and deploy integration

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd2020#19]

**Comment by palnabarun** [comment]
Hi @bhansa 👋🏽 -- can you elaborate a bit more on the CI and deployment setup of the website? And, what is the issue with CI build and deploy integration?

Thank you! 👍🏽

**Comment by bhansa** [comment]
Hi @palnabarun 

The current deployment is happening through **travis ci** and there is an issue related to authentication between travis and github. I had created a secure for travis using GH_TOKEN from my profile but travis could not authenticate the remote repository.

Below is how the deployment process works: 
 - we push code to this repository.
 - travis detects the changes and triggers the build and run script [deploy.sh](https://github.com/HydPy/pyconfhyd2020/blob/main/deploy.sh)
 - site output is generated and copied into https://github.com/HydPy/hydpy.github.io in respective folder.  [**_Breaks here_**]

Travis Dashboard: https://travis-ci.com/github/HydPy/pyconfhyd2020.

Let me know if you need any more inputs, we can discuss over [zulip](https://hydpy.zulipchat.com) 😊

**Comment by bhansa** [comment]
+ @inovizz

**Comment by inovizz** [comment]
ok, sorry I missed replying back here. This has been taken care of. However, netlify previews are not working because of the folder structure we are following. I'll create a separate issue for this.

deployment is fixed after we moved to Github Actions.

cc @bhansa @palnabarun
