### ISSUE TITLE
Add social links on website

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd2020#20]
**Twitter**: https://twitter.com/pyconfhyd
**Github**: https://github.com/HydPy/pyconfhyd2020

**Comment by jabhishek87** [comment]
Is that still Open ? i would like to help

**Comment by bhansa** [comment]
@jabhishek87 It is still open, please send a PR with a preview link if possible.
Let me know if you need any help :)

**Comment by bhansa** [comment]
updated in #37
