### ISSUE TITLE
Add Community Partner(s)

### ISSUE THREAD

**Issue by GoelJatin** [HydPy/pyconfhyd2020#30]
1. PyLadies Hyderabad
  - Logo - https://drive.google.com/file/d/0B4w3DrsBt8CjSkxGblFhOW9FaFk/view?usp=sharing
  - Website - https://pyladies.hydpy.org/
  - Twitter - pyladieshyd

2. ILUG Delhi
  - Logo - https://github.com/ILUGD/Assets/blob/master/svg/logo_ilugd.svg
  - Twitter - ilugdelhi

3. ChennaiPy
  - Logo - https://github.com/Chennaipy/logo-contest/blob/master/vengatesh.png (Last one to be used)
  - Twitter - chennaipy

4. Co-Learning Lounge
  - Logo - 
![image](https://user-images.githubusercontent.com/14715892/98141886-27dfe880-1eed-11eb-9486-232077bb99d7.png)

  - Website - https://colearninglounge.com/
  - Twitter - ColearninLounge

5. GDG Chennai
  - Logo - https://twitter.com/GDGChennai/photo
  - Twitter - GDGChennai

More to come.. :)

**Comment by bhansa** [comment]
Addressed in #31

**Comment by GoelJatin** [comment]
Added another partner and updated GDG Chennai logo - https://github.com/HydPy/pyconfhyd2020/pull/34

**Comment by GoelJatin** [comment]
Added Python Pune in https://github.com/HydPy/pyconfhyd2020/pull/35

**Comment by GoelJatin** [comment]
Added all partners
