### ISSUE TITLE
Speaker and talks details are to be added for all of the speakers in the schedule

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020#55]
- [ ] data to be provided by sanchit
- [ ] someone to refractor the code and update the website with same

**Comment by bkamapantula** [comment]
I can pick this up, will use the existing format that works for the keynote speakers. Information needed:

- speaker name
- title
- website or a link
- speaker image
- speaker background

this will go under `_speakers/` directory, one for each speaker.

**Comment by inovizz** [comment]
Hi @bkamapantula - you should have all details from the CFP dump you got. Please feel free to use it. I'll share speaker images with you by tomorrow.

**Comment by bkamapantula** [comment]
@inovizz the sheet I've has no speaker details, could you please share one with them?

**Comment by bhansa** [comment]
Closing it, as it is done.
