### ISSUE TITLE
Paul Ganssle's keynote box in the schedule doesn't have correct background color

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020#56]
Currently, the background colour for Paul's keynote schedule on the first day is coming as grey, it should consistent as the first keynote

**Comment by bkamapantula** [comment]
it seems to be OK now, please review?

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/99898314-7f8c9b00-2cc6-11eb-9856-3b178cce1590.png)

**Comment by inovizz** [comment]
for me, it comes like this.

**Comment by bkamapantula** [comment]
ah, I see. I assumed the top list of keynote speakers. please ignore me.

**Comment by bhansa** [comment]
Shall we close this, if no longer required.

**Comment by inovizz** [comment]
It is still not fixed.
