### ISSUE TITLE
Deploy preview is unavailable in PR builds

### ISSUE THREAD

**Issue by suryahanumandla** [HydPy/pyconfhyd2020#75]
After the PR check build, deployed build is failed to find resources and preview is unavailable.
![image](https://user-images.githubusercontent.com/7765847/100384056-3bdabe00-3045-11eb-8e29-632b11df711d.png)

I tried with removing **2020** from the URL, could see able to access it properly.

**Comment by inovizz** [comment]
yes, I need to work on this issue. Will fix it. Thanks for creating the issue @suryahanumandla.

**Comment by suryahanumandla** [comment]
Looks like it got fixed @inovizz shall I close this one.

**Comment by bhansa** [comment]
Yes, it is fixed now. Closing this.
