### ISSUE TITLE
Speaker icon alignment is missing in mobile view

### ISSUE THREAD

**Issue by suryahanumandla** [HydPy/pyconfhyd2020#79]
![image](https://user-images.githubusercontent.com/7765847/100419819-4a5bc080-30ab-11eb-8e9d-6d7256b0b337.png)

**Comment by bhansa** [comment]
I will work on this @suryahanumandla

**Comment by suryahanumandla** [comment]
fix is available  @bhansa 
I've continuous meeting, will raise PR once I'm done with it.

**Comment by bhansa** [comment]
Sure, please take your time.

**Comment by suryahanumandla** [comment]
It has been fixed in #80
